resolver: lts-8.21

packages:
- '.'
- location:
    git: https://github.com/jaspervdj/hakyll.git
    commit: a0a819aa61f5fad90d5bb48f1e14751b7848a844
  extra-dep: true

extra-deps:
- containers-0.5.10.2
- pandoc-citeproc-0.10.5.1

nix:
  pure: false
  packages: [zlib]
